# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32f89ff74fe9bb65401732f6112a27f446e1e85046ce72846c2c28a1152681baea0e3de4ae50ba6f90c92f1649f59aaf4ccb5acad30c054ed2e202d1994d2259

test:
  secret_key_base: d6ed9f9232451e31bed20a64b0a3fb23057257822ad3a65631dc965b3c2ef458443765554d7aaa3c347aa91683cc22339a612497a100a16628859e65466b4a0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
